---
- name: Install PHP5
  apt: pkg=php5
  tags: php

- name: Install PHP5 libraries
  apt: pkg={{ item }}
  with_items:
   - php5-curl
   - php5-cli
   - php5-fpm
   - php5-mysql
   - php5-mcrypt
   - php5-gd
   - php5-xdebug
  tags: php

- name: Make mcrypt configuration file
  shell: echo 'extension=/usr/lib/php5/20121212/mcrypt.so' > {{ item }}
  with_items:
   - /etc/php5/mods-available/mcrypt.ini
   - /etc/php5/cli/conf.d/20-mcrypt.ini
   - /etc/php5/fpm/conf.d/20-mcrypt.ini
  tags: php

- name: Create PHP5 configuration file
  copy:
    src=php-fpm.conf
    dest=/etc/php5/fpm/php-fpm.conf
  tags: php

- name: Create FPM configuration file
  copy: 
    src=www.conf
    dest=/etc/php5/fpm/pool.d/www.conf
  tags: php

#- include: composer.yml

