---
- name: Install PHP5
  apt: pkg=php5
  tags: php

- name: Install PHP5 command line interface
  apt: pkg=php5-cli
  tags: php

- name: Install PHP5 CGI library
  apt: pkg=php5-cgi
  tags: php

- name: Install PHP5 FPM library
  apt: pkg=php5-fpm
  tags: php

- name: Install PHP5 mysql driver
  apt: pkg=php5-mysql
  tags: php

- name: Install PHP5 mcrypt library
  apt: pkg=php5-mcrypt
  tags: php

- name: Install PHP5 gd library
  apt: pkg=php5-gd
  tags: php

- name: Install PHP5 xdebug
  apt: pkg=php5-xdebug
  tags: php

- name: Create PHP5 configuration file
  copy: src=php-fpm.conf dest=/etc/php5/fpm/php-fpm.conf
  tags: php

- name: Create FPM configuration file
  copy: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  tags: php

#- include: composer.yml

